#!/bin/bash
#
# Dependencies:
#   (both local and remote host): ssh, scp, tar 
#   (only local): hg, uci
# Getting uci for yourself is really easy:
#   uci git clone git://nbd.name/uci.git
# (compilation is a breeze)
# or simply redefine getIpFromUciConfig()
#
#       Copyleft 2012 Gui Iribarren <gui@altermundi.net>
#       
#       This program is free software; you can redistribute it and/or modify
#       it under the terms of the GNU General Public License as published by
#       the Free Software Foundation; either version 2 of the License, or
#       (at your option) any later version.
#       
#       This program is distributed in the hope that it will be useful,
#       but WITHOUT ANY WARRANTY; without even the implied warranty of
#       MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#       GNU General Public License for more details.
#       
#       You should have received a copy of the GNU General Public License
#       along with this program; if not, write to the Free Software
#       Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#       MA 02110-1301, USA.
#
### 
### Usage: $0 push [-n] [-f|-q] [-w secs] [-i <host>] NAME [[-i <host>] NAME] ...
###        $0 pull [-z] [-i <host>] NAME [[-i <host>] NAME] ...
###        $0 confirm NAME [NAME] ...
###        $0 status [-f] [-i <host>] NAME [[-i <host>] NAME] ...
### 
### Manage remote uci configuration in NAME(s)
### 
###  -w, --wait NUM	  After applying configuration, wait for NUM seconds
###                     before reboot.
###  -i, --ip HOST		Override the IP used for pull, push, status...
###                     Applies only to the next NAME specified in command line.
###  -n, --no-reboot	Prevent rebooting after pushing and applying configuration.
###  -z, --gzip       Use gzip compression on incoming network traffic during pull.
###                     Better perfomance on slow links, at the expense of high cpu load.
###  -f, --full       Push (or check) whole /overlay instead of just /overlay/etc.
###                     Increases network traffic = slower perfomance.
###                     Useful to check for package installs or removals
###                     or to push a complete overlay to a clean install of openwrt.
###  -q, --quick      Push only a small subset of files in /etc that don't need reboot,
###                     such as /etc/hosts. Implies -n, overrides -f.
###
#
#

export REBOOT_WAIT=15  # in seconds #DEPRECATED
export TIMEOUT=15  # in seconds
export REBOOT_CMD="/usr/sbin/safe-reboot now &>/tmp/safe-reboot.log"
export NO_REBOOT_CMD="/bin/true"
export TAR="tar" # This command must accept argument -z to enable gzip compression
export CMDNAME="$(basename "$0")"
export SSH_PERSIST="ssh -o \"ControlMaster auto\" \
                    -o \"ControlPath /tmp/${CMDNAME}_ssh_%r@%h:%p\" \
                    -o \"ControlPersist 60\" \
                    -o \"ServerAliveInterval 10\" \
                    -o \"ConnectTimeout 20\" \
                   "
export EPOCH="$(date +%s)"

export DIR_OVERLAY="overlay"
export DIR_UCI_CONFIG="$DIR_OVERLAY/etc/config/"
export DIR_PULL_TMP="remote.$EPOCH"
export DIR_TO_DIFF="${DIR_OVERLAY:?}/etc"
export DIR_PUSH_TMP="overlay.new.$EPOCH"
export DIR_TO_PUSH="etc/"
export FILES_TO_QUICK_PUSH="etc/{dropbear/authorized_keys,bat-hosts,hosts,profile,shadow}"
export ETC_FAILSAFE="etc.last-good/"

export CNAMES_PUSHED="/tmp/ruci.pushed.$EPOCH"
export CNAMES_DIRTY="/tmp/ruci.dirty.$EPOCH"
export TMP_CLONE="/tmp/ruci.hgclone.$EPOCH"
cat /dev/null >"${CNAMES_PUSHED:?}"
cat /dev/null >"${CNAMES_DIRTY:?}"

usage () { REASON="$*"
  [ -n "$REASON" ] && echo "$REASON"
  sed -n "/^### /{s///;s|\$0|$CMDNAME|g;p}" "$0"
  exit 1
}

getIpFromUciConfig () { 
  uci -c "$DIR_UCI_CONFIG" get system.@system[0].hostname
}

repoIsClean () {
  repoIsEqualToRev "-1"
}

repoIsEqualToRev () { REV="${1:?}" ; DIR="${2:-$DIR_OVERLAY}"
  STDOUT="$(hg diff --rev $REV "$DIR")" ; RETVAL=$?
  ([ -z "$STDOUT" ] && [ $RETVAL -eq 0 ]) && return 0 || return 1
}

repoAutocommit () {
  hg commit -A -m "Autocommit local changes before pulling." "$DIR_OVERLAY"
}

repoLastRev () {
  hg log --template "{node}\n" -l 1 "$DIR_OVERLAY"
}

writeLastRevPushed () {
  repoLastRev > ".lastrevpushed"
}

readLastRevPushed () {
  [ -s ".lastrevpushed" ] && cat ".lastrevpushed" || echo 0
}

tstamp () {
  date +%F_%T.%3N
}

log () { TEXT="$*"
  [ "$1" == "*" ] && CNAME="*" || CNAME="$(basename `pwd -L`)"
  echo "$TEXT" \
    | sed "/tar: removing leading ... from member/d" \
    | sed "s|^|[$CNAME] $(tstamp): |" \
    | tee -a "$LOGFILE"
}
 
try () { CMDLINE="${1:?}"
  CMD="${CMDLINE%% *}"
  CNAME="$(basename `pwd -L`)"
  ERRLOG="/tmp/$CMD.${CNAME////}.$EPOCH"
  
  eval "$CMDLINE" &> "$ERRLOG"
  RETVAL=$?
  if [ -r "$ERRLOG" ] && [ -s "$ERRLOG" ] ; then
    sed "s|^|($CMD) |" -i "$ERRLOG"
    log "$(<"$ERRLOG")"
  fi
  rm -f "$ERRLOG"
  return $RETVAL
}

pullConfigFromIp () { IPADDR="${1:?}"
  RETVAL=
  
  if [ -d "$DIR_OVERLAY" ] && ! repoIsClean ; then
    log "Directory contains uncommited changes. Autocommiting..."
    try "repoAutocommit" \
      || return
  fi

  mkdir -p "$DIR_PULL_TMP"

  log "Pulling /$DIR_OVERLAY from $IPADDR ..."
  try "$SSH_PERSIST $IPADDR \"$TAR -c -f - /$DIR_OVERLAY \" >$DIR_PULL_TMP.tar" \
    || { RETVAL=$? ; rm -rf "$DIR_PULL_TMP"{/,.tar} ; return $RETVAL ; }
  
  try "$TAR -x -f $DIR_PULL_TMP.tar -C $DIR_PULL_TMP" \
    || { RETVAL=$? ; rm -rf "$DIR_PULL_TMP"{/,.tar} ; return $RETVAL ; }

  rm -rf "$DIR_PULL_TMP/$DIR_OVERLAY/$ETC_FAILSAFE" # Ignore the temp $ETC_FAILSAFE on remote hosts
  rm -rf "$DIR_PULL_TMP.tar"
  rm -rf "$DIR_OVERLAY"
  mv "$DIR_PULL_TMP/$DIR_OVERLAY" "$DIR_OVERLAY"
  rm -rf "$DIR_PULL_TMP"
  
  log "Pulled successfully."
}

pushConfigToIp () { IPADDR="${1:?}"
  RETVAL=
  PUSH_FILES=
  
  try "$TAR -c --owner root --group root -f $DIR_PUSH_TMP.tar -C $DIR_OVERLAY/ ./$DIR_TO_PUSH" \
    || { RETVAL=$? ; rm -rf "$DIR_PUSH_TMP.tar" ; return $RETVAL ; }
    
  log "Sending ${DIR_TO_PUSH:-/$DIR_OVERLAY} with '$TAR' to $IPADDR ... "
  try "$SSH_PERSIST $IPADDR \"/bin/mkdir -p /tmp/$DIR_PUSH_TMP/\" " \
    || return

  try "$SSH_PERSIST $IPADDR \"$TAR -x -f - -C /tmp/$DIR_PUSH_TMP/ \" <$DIR_PUSH_TMP.tar" \
    || { RETVAL=$? ; rm -rf "$DIR_PUSH_TMP.tar" ; return $RETVAL ; }
  
  rm -rf "$DIR_PUSH_TMP.tar"

  log "Config sent. Applying changes..."
  if [ "$DIR_TO_PUSH" != "$FILES_TO_QUICK_PUSH" ] ; then
    log "Sending $DIR_TO_PUSH"
    try "$SSH_PERSIST $IPADDR ' export PATH=\"/bin:/sbin:/usr/bin:/usr/sbin\" ; cd /$DIR_OVERLAY \
                              &&  rm -rf $ETC_FAILSAFE \
                              &&  (  cp -a etc $ETC_FAILSAFE \
                                  && cp -a etc /tmp/$DIR_PUSH_TMP/$ETC_FAILSAFE \
                                  && rm -rf ${DIR_TO_PUSH:-*} \
                                  && cp -a /tmp/$DIR_PUSH_TMP/${DIR_TO_PUSH:-*} . ) \
                              &&  (  sleep $REBOOT_WAIT \
                                  && $REBOOT_CMD & ) ' " \
      || return

    writeLastRevPushed
  else
    log "Sending quick"
    try "$SSH_PERSIST $IPADDR '  cd /$DIR_OVERLAY \
                              &&  rm -rf $ETC_FAILSAFE \
                              &&  (  cp -a etc $ETC_FAILSAFE \
                                  && cp -a /tmp/$DIR_PUSH_TMP/etc/* /etc/ ) ' " \
      || return
  fi

  log "Done.$([ "$REBOOT_CMD" == "$NO_REBOOT_CMD" ] || echo " Rebooting in $REBOOT_WAIT secs...")"

  CNAME="$(basename `pwd -L`)"
  echo -n " $CNAME" >> "$CNAMES_PUSHED"
}

confirmConfigToIp () { IPADDR="${1:?}"
  log "Trying to remove $ETC_FAILSAFE in $IPADDR ... "
  try "$SSH_PERSIST $IPADDR \"/bin/rm -rfv /$DIR_OVERLAY/${ETC_FAILSAFE:?}\" " \
    || return

  log "Done."
}

statusConfigFromIp () { IPADDR="${1:?}"
  RETVAL=
  STATUSMSG=
  
  CNAME="$(basename `pwd -L`)"
  
  # Clone the repo to make comparisons
  try "cp -a \"$(hg root)\" \"$TMP_CLONE-$CNAME/\" >/dev/null" \
    || return 1
  rm -f "$TMP_CLONE-$CNAME/.hg/hgrc"
    
  # cd to the temp repo clone
  cd $(pwd|sed "s!$(hg root)!$TMP_CLONE-$CNAME/!") \
    || return 2

  log "Pulling /$DIR_TO_DIFF from $IPADDR ..." >/dev/null
  # Try to pull remote /overlay. If it fails, cleanup .tar tempfile.
  try "$SSH_PERSIST $IPADDR \"$TAR -c -f - /$DIR_TO_DIFF \" >$DIR_PULL_TMP.tar" \
    || { rm -rf "${TMP_CLONE:?}-${CNAME:?}/" ; return ; }
  
  # Unpack recently pulled /overlay
  rm -rf "$DIR_TO_DIFF"
  try "$TAR -x -f $DIR_PULL_TMP.tar"
  
  # Clean up and prepare comparison
  rm -rf "$DIR_PULL_TMP.tar"          
  rm -rf "$DIR_OVERLAY/$ETC_FAILSAFE" # Ignore the temp $ETC_FAILSAFE on remote hosts
  hg addremove "$DIR_TO_DIFF" >/dev/null 
  log "Pulled successfully."  >/dev/null

  # Check if remote has $ETC_FAILSAFE present, suggesting it's on the countdown
  try "$SSH_PERSIST $IPADDR /bin/sh -c \'[ -d /$DIR_OVERLAY/$ETC_FAILSAFE ]\' " \
    && STATUSMSG=" Counting down to revert-to-lastgood..." \
    && echo -n " $CNAME" >> "$CNAMES_PUSHED"
  
  repoIsEqualToRev "-1" "$DIR_TO_DIFF" ; RETVAL=$?
  
  [ -z "$(hg status --rev $REV "$DIR")" ] ; RETVAL=$(( $RETVAL + $?))

  case $RETVAL in
    0)      # Local and remote copies are equal, that means we can consider the current revision as pushed
            # even if it wasn't done with "action push". So, update LastRevPushed cookie
            # If you do "hg commit; ruci push; hg rollback; ...; hg commit", then a simple
            # "ruci status" should update/fix cookies that point to vanished changeset ids.
      ( cd $OLDPWD && writeLastRevPushed )
      log "$IPADDR Reachable and updated.$STATUSMSG"
    ;;
    *)      # If copies differ, might be because local has a new revision waiting to be pushed,
            # (in which case working copy is identical to the one in revision readLastRevPushed)
      hg commit -m "Fresh overlay for comparison"
      try "hg diff --stat --rev -1 --rev -2 \"$DIR_TO_DIFF\" " >/dev/null
      if repoIsEqualToRev "$(readLastRevPushed)" "$DIR_TO_DIFF" ; then
        log "$IPADDR Reachable, outdated. Remote revision $(readLastRevPushed|cut -b -12) .$STATUSMSG"
      else  # or else because changes happened only remotely.
        log "$IPADDR Reachable, with remote untracked changes. Please pull, manually merge and commit.$STATUSMSG"
      fi
      echo -n "${CNAME}|" >> "$CNAMES_DIRTY"
    ;;
  esac
  
  # Clean up the comparison scenario and leave everything as it was previously
  rm -rf "${TMP_CLONE:?}-${CNAME:?}/"
}

pullConfigs () {
  ARG=
  IPADDR=
  
  while [ -n "$1" ]; do
    ARG="$1"
    shift
  
    case "$ARG" in
      -i|--ip ) IPADDR="$1" ; shift ;;
      -z|--gzip ) TAR="$TAR -z" ;;
      * )
        mkdir -p "$ARG"
        cd "$ARG"
          if ! [ -d "$DIR_UCI_CONFIG" ] && [ -z "$IPADDR" ] ; then 
            log "UCI config directory not found! Please prepend --ip to specify where to pull from."
            continue
          fi
    
          [ -z "$IPADDR" ] && IPADDR=$(getIpFromUciConfig)
    
          pullConfigFromIp "$IPADDR" &
        cd "$OLDPWD"
        
        unset IPADDR
      ;;
    esac
  done
}

pushConfigsSafe () {
  ARG=
  IPADDR=
    
  # Parse args and populate targets list
  while [ -n "$1" ]; do
    ARG="$1"
    shift
  
    case "$ARG" in
      -i|--ip ) IPADDR="$1"; shift ;;
      * )
        cd "$ARG"
          [ -d "$DIR_UCI_CONFIG" ] \
            || { log "UCI config directory not found! All targets must be valid. Aborting..." ; exit 1 ; }

          [ -z "$IPADDR" ] && IPADDR=$(getIpFromUciConfig)
    
          # Check local repo is clean
          if ! repoIsClean ; then
            log "Directory contains uncommited changes. Please commit first. Aborting..." ; exit 2
          fi
        cd "$OLDPWD"
        
        unset IPADDR
      ;;
    esac
  done
  
        RETVAL=
        PUSH_FILES=
  
        # Open ssh persistent connection
        try "$SSH_PERSIST $IPADDR /bin/sh -c \'[ -d /$DIR_OVERLAY/$ETC_FAILSAFE ]\' "
          RETVAL=$?
          if [ $RETVAL -eq 0 ] ; then
            log "Previous push hasn't been confirmed yet. Use \`$CMDNAME confirm ...\` first. Aborting..." 
            exit 3
          fi

        #   pull and check against last rev ; wait
        #      [if not clean, exit "try hg merge"]
        #   copy files ; wait ; "config sent"
        #   swap /etc /etc.fsf ; wait ; "New config in place"
        #   reboot ; "Reboot"
        # close ssh persistent connection
        # ping ; wait
        # open ssh persistent connection
        #   remove /etc.fsf
        # close ssh persist
        # save last rev name pushed
        
#####
        
####
}

pushConfigs () {
  ARG=
  IPADDR=
  
  while [ -n "$1" ]; do
    ARG="$1"
    shift
  
    case "$ARG" in
      -i|--ip ) IPADDR="$1" ; shift ;;
      -n|--no-reboot ) REBOOT_CMD="$NO_REBOOT_CMD" ;;
      -f|--full ) unset DIR_TO_PUSH ;;
      -q|--quick ) DIR_TO_PUSH="$FILES_TO_QUICK_PUSH" ; REBOOT_CMD="$NO_REBOOT_CMD" ;;
      -w|--wait ) 
        if [ -z "${1//[0-9]/}" ] ; then
          REBOOT_WAIT=$1 ; shift
        else usage "Error: Wait delay must be an integer"
        fi
      ;;
      * )
        if cd "$ARG" ; then
          [ -d "$DIR_UCI_CONFIG" ] \
            || { log "UCI config directory not found. Ignoring host." ; unset IPADDR ; continue ; }
    
          [ -z "$IPADDR" ] && IPADDR=$(getIpFromUciConfig)
    
          pushConfigToIp "$IPADDR" &
        cd "$OLDPWD"
        fi
        
        unset IPADDR
      ;;
    esac
  done
}

confirmConfigs () {
  ARG=
  IPADDR=
  
  while [ -n "$1" ]; do
    ARG="$1"
    shift
  
    cd "$ARG"
      [ -d "$DIR_UCI_CONFIG" ] \
        || { log "UCI config directory not found. Ignoring host." ; continue ; }
      
      IPADDR=$(getIpFromUciConfig)

      confirmConfigToIp "$IPADDR" &
    cd "$OLDPWD"
  done
}

statusConfigs () {
  ARG=
  IPADDR=
  
  while [ -n "$1" ]; do
    ARG="$1"
    shift
    
    case "$ARG" in
      -f|--full ) DIR_TO_DIFF="$DIR_OVERLAY" ;;
      -i|--ip ) IPADDR="$1" ; shift ;;
      * )
        cd "$ARG"
          [ -d "$DIR_UCI_CONFIG" ] \
            || { log "UCI config directory not found. Ignoring host." ; unset IPADDR ; continue ; }
          
          [ -z "$IPADDR" ] && IPADDR=$(getIpFromUciConfig)
          
          statusConfigFromIp "$IPADDR" &
        cd "$OLDPWD"
        
        unset IPADDR
      ;;
    esac
  done
}

export ACTION="$1"
shift

export LOGFILE="/tmp/$CMDNAME-$ACTION.log"
rm -f "$LOGFILE"

case "$ACTION" in
  pull | push | confirm ) 
    [ -z "$*" ] && usage "Error: No NAME(s) specified on command line."
    ${ACTION}Configs "$@"
  ;;
  status )
    if [ -z "$*" ] ; then 
      ${ACTION}Configs *
    else 
      ${ACTION}Configs "$@"
    fi
  ;;
  "" ) usage ;;
  * ) usage "Error: Unknown action \"$ACTION\"" ;;
esac

log "*" "All jobs started. Sorted logfile will be written to $LOGFILE"
wait
sort "$LOGFILE" | sed "/\(Pulling\|Sending\|Trying\)/s/^/\n/" > "$LOGFILE".sort
mv -f "$LOGFILE.sort" "$LOGFILE"

echo
[ -s "$CNAMES_DIRTY" ] && egrep "($(<"$CNAMES_DIRTY")^$)" "$LOGFILE" | uniq
[ -s "$CNAMES_PUSHED" ] && echo -e "Don't forget to run:\n$CMDNAME confirm $(<"$CNAMES_PUSHED")"
rm -rf "${CNAMES_DIRTY:?}" "${CNAMES_PUSHED:?}"
